# Generated by Django 6.0.5 on 2026-06-19 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exclusions', '0005_californiaexclusion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CaliforniaExclusion',
            new_name='StagingCalifornia',
        ),
        migrations.RenameModel(
            old_name='GeorgiaExclusion',
            new_name='StagingGeorgia',
        ),
        migrations.RenameModel(
            old_name='Exclusion',
            new_name='StagingOIG',
        ),
    ]
