# Generated by Django 6.0.5 on 2026-06-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exclusions', '0006_rename_californiaexclusion_stagingcalifornia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('business_name', models.CharField(blank=True, db_index=True, max_length=512)),
                ('npi', models.CharField(blank=True, db_index=True, max_length=20)),
                ('general', models.CharField(blank=True, max_length=255)),
                ('specialty', models.CharField(blank=True, max_length=255)),
                ('provider_type', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=512)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, db_index=True, max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('exclusion_type', models.CharField(blank=True, max_length=20)),
                ('exclusion_date', models.DateField(blank=True, db_index=True, null=True)),
                ('reinstatement_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, db_index=True, max_length=50)),
                ('source_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'main_exclusion',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['state', 'exclusion_date'], name='main_state_date_idx'), models.Index(fields=['source'], name='main_source_idx'), models.Index(fields=['npi'], name='main_npi_idx')],
            },
        ),
    ]
