# Generated by Django 6.0.5 on 2026-06-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exclusions', '0007_mainexclusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='StagingNewYork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, db_index=True, max_length=512)),
                ('npi', models.CharField(blank=True, db_index=True, max_length=20)),
                ('license_number', models.CharField(blank=True, max_length=255)),
                ('provider_type', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, db_index=True, max_length=2)),
                ('exclusion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'staging_new_york',
                'ordering': ['business_name'],
            },
        ),
    ]
