# Generated by Django 6.0.5 on 2026-06-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exclusions', '0009_stagingohio'),
    ]

    operations = [
        migrations.CreateModel(
            name='StagingNorthDakota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(blank=True, db_index=True, max_length=512)),
                ('business_name', models.CharField(blank=True, db_index=True, max_length=512)),
                ('npi', models.CharField(blank=True, db_index=True, max_length=20)),
                ('license_number', models.CharField(blank=True, max_length=255)),
                ('provider_type', models.CharField(blank=True, max_length=255)),
                ('sanction_type', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=512)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, db_index=True, max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('exclusion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'staging_north_dakota',
                'ordering': ['provider_name'],
            },
        ),
    ]
