# Generated by Django 6.0.5 on 2026-06-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exclusions', '0010_stagingnorthdakota'),
    ]

    operations = [
        migrations.CreateModel(
            name='StagingNorthCarolina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluded_entity', models.CharField(blank=True, db_index=True, max_length=512)),
                ('npi', models.CharField(blank=True, db_index=True, max_length=20)),
                ('exclusion_date', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, db_index=True, max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('ownership', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'staging_north_carolina',
                'ordering': ['excluded_entity'],
            },
        ),
    ]
