# Generated by Django 6.0.5 on 2026-06-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exclusions', '0012_stagingoregon'),
    ]

    operations = [
        migrations.CreateModel(
            name='StagingPennsylvania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('business_name', models.CharField(blank=True, db_index=True, max_length=512)),
                ('npi', models.CharField(blank=True, db_index=True, max_length=20)),
                ('license_number', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=512)),
                ('state', models.CharField(blank=True, db_index=True, max_length=2)),
                ('exclusion_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'staging_pennsylvania',
                'ordering': ['last_name', 'first_name', 'business_name'],
            },
        ),
    ]
