# Generated by Django 6.0.5 on 2026-06-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exclusions', '0013_stagingpennsylvania'),
    ]

    operations = [
        migrations.CreateModel(
            name='StagingNewJersey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, db_index=True, max_length=512)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('npi', models.CharField(blank=True, db_index=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=512)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, db_index=True, max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('action', models.CharField(blank=True, max_length=255)),
                ('exclusion_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'staging_new_jersey',
                'ordering': ['business_name'],
            },
        ),
    ]
